### ISSUE TITLE
Undefined function or variable 'SVC_raw'

### ISSUE THREAD

**Issue by payymann** [ohadf/distractors#1]
After downloading all dependencies and doing all works mentioned in external/README, when I run "demo_predict.m" an error appears that complains about "SVC_raw" function. Here is the output of this script : 

```
>> demo_predict
WARNING: Database pascal2012 (folder JPEGImages) not found in /path/to/pascal2012/
WARNING: Database SBD (folder images) not found in /path/to/SBD/
WARNING: Database COCO (folder images) not found in /path/to/COCO/
-- You can disable this warning in install.m --
-- Successful installation of MCG. Enjoy! --
Finding Color channels...0.10542 seconds 
Finding probabilities of colors at blur level...0, 2, 4, 8, 16, 4.1512 seconds 
Finding horizon...0.75956 seconds 
Finding cars...3.0794 seconds 
Finding people...3.6559 seconds 
Finding faces...Scale : 19.2 objects detected : 0
Scale : 16 objects detected : 0
Scale : 13.3333 objects detected : 0
Scale : 11.1111 objects detected : 0
Scale : 9.2593 objects detected : 0
Scale : 7.716 objects detected : 2
Scale : 6.43 objects detected : 2
Scale : 5.3584 objects detected : 2
Scale : 4.4653 objects detected : 2
Scale : 3.7211 objects detected : 2
Scale : 3.1009 objects detected : 2
Scale : 2.5841 objects detected : 2
Scale : 2.1534 objects detected : 2
Scale : 1.7945 objects detected : 2
Scale : 1.4954 objects detected : 2
Scale : 1.2462 objects detected : 2
Scale : 1.0385 objects detected : 2
2.0238 seconds 
Finding text...1.695 seconds 
Finding distance to the center...0.026189 seconds 
Finding distance to the closest border...0.011738 seconds 
Finding Itti&Koch channels...
Saliency Toolbox (http://www.saliencytoolbox.net)
For licensing details type 'STBlicense' at the prompt.

1.0156 seconds 
Finding Torralba saliency...0.14033 seconds 
Finding Hou saliency (NIPS 2008)...0.39225 seconds 
Finding PCA saliency...1.4849 seconds 
Finding Coxel saliency...Undefined function or variable 'SVC_raw'.
```

Where is this function defined? I have searched all source files in this repo and there is no definition for this function.

*** I am trying the code with Matlab R2016b on ubuntu 16.04.

**Comment by ohadf** [comment]
It depends on the version of Coxel Saliency you are using. The SVC_raw() function has different names in different versions.
You need to locate the new name and use it instead of SVC_raw. Alternatively, you can drop Coxel Saliency all together. 
From the docs:
"Note: omitting this feature, our model still performs well. Thus, if you are having trouble obtaining the code, simply omit the feature. This will also speed up feature calculation, since coxel features are the slowest to compute out of all our features."

**Comment by fardinSS** [comment]
in new version they renamed those functions :
SVC_raw() ----> CEOS_rawData()
SVC_map() ----> CEOS_smap
